icd10_llmops:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: sfsenorthamerica-moizahmeddemo
      user: MAHMED
      authenticator: externalbrowser
      role: ACCOUNTADMIN
      warehouse: XSMALL_WH
      database: ASPEN_AI_POC
      schema: ICD10_DEMO
      threads: 4
